"""
Block-specific prompt assembly for the cache-warmed parallel prep path.

Reuses ROLE / LOCALIZATION_POLICY / BLOCK_SCHEMA text straight out of
src/Deepseek/prompt/prep_prompt_deepseek_en.xml (the unified path's prompt) instead of
re-authoring 15 blocks' worth of instructions a second time — one drift
surface is enough. See PARALLEL_PREP_GUIDE.md §3 for why the system prompt
below must be byte-identical across EVERY call in a run, Pro's included: the
block-specific instruction is the one thing allowed to vary, so it lives
entirely in the user-turn's trailing <BLOCK_TASK>, never in <system>.

build_shared_system_prompt()/build_shared_prefix() below exist to test a
theory: if Pro's own Phase 1 call shares its leading bytes with every Phase
2 Flash call, the ~30-50K-token jp_chapters block might only need processing
fresh ONCE per prep run (by Pro) instead of twice.

Status: UNCONFIRMED, don't trust it. dev/test_cross_model_cache.py's Test B
(a throwaway system prompt) showed a Pro call cleanly warming a Flash call's
cache, first-ever exposure included — that's what motivated this. Test C
immediately after ran the identical cross-model check through these actual
functions (real ROLE+LOCALIZATION_POLICY system prompt, real task-suffix
text) and got a clean miss instead. No documented mechanism explains the
gap; treat the restructuring below as request-shape hygiene that MIGHT
occasionally save a fresh jp_chapters pass, not as a proven cost win. It
does not change correctness either way, and a sequential Flash warming call
is still required before the 12 parallel calls regardless of outcome.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, Tuple

from src.Deepseek.common.config import PIPELINE_ROOT, get_config_section

# ══════════════════════════════════════════════════════════════════════════
# Block ownership — must sum to the 15 fillable blocks in the barebone
# context.xml (character_attribute_anchors is the one block no lightweight
# client here ever touches; see prep_prompt_deepseek_en.xml OUTPUT_CONTRACT).
# ══════════════════════════════════════════════════════════════════════════

PRO_BLOCKS: Tuple[str, ...] = ("character_roster", "name_map")

FLASH_BLOCKS: Tuple[str, ...] = (
    "validation_audit",
    "volume_identity",
    "chapter_titles_en",
    "world_setting",
    "relationship_graph",
    "verbatim_anchors",
    "voice_fingerprints",
    "cultural_glossary",
    "eps_arc_tracker",
    "eps_signals",
    "scene_plans",
    "illustration_context",
    "translation_brief",
)

# ══════════════════════════════════════════════════════════════════════════
# Multi-turn prep — one sequential turn per block, same order every time.
# Must match src/prep/agent.py::_BLOCK_NAMES (the Librarian's placeholder
# context.xml order) with chapter_titles_en inserted right after
# volume_identity (same relative position FLASH_BLOCKS above uses, since the
# prompt's own volume_identity schema ties title_en and chapter_titles_en
# together as one thematic set) and character_attribute_anchors omitted
# entirely — that block is never generated by any lightweight-client path,
# unified or parallel, and multi-turn keeps that behavior.
# ══════════════════════════════════════════════════════════════════════════

MULTITURN_BLOCK_ORDER: Tuple[str, ...] = (
    "validation_audit",
    "volume_identity",
    "chapter_titles_en",
    "world_setting",
    "character_roster",
    "name_map",
    "relationship_graph",
    "verbatim_anchors",
    "voice_fingerprints",
    "cultural_glossary",
    "eps_arc_tracker",
    "scene_plans",
    "eps_signals",
    "illustration_context",
    "translation_brief",
)


class PromptSchemaError(RuntimeError):
    """Raised when prep_prompt_deepseek_en.xml doesn't contain an expected section."""


# ══════════════════════════════════════════════════════════════════════════
# Source-of-truth extraction (regex, not ET — the schema text contains
# &lt;tag&gt; escapes meant to be read literally as prose, not re-parsed)
# ══════════════════════════════════════════════════════════════════════════

_SECTION_RE_CACHE: Dict[str, re.Pattern] = {}
_BLOCK_RE = re.compile(r'<block name="([^"]+)">(.*?)</block>', re.DOTALL)

_raw_prompt_cache: str | None = None
_block_schema_cache: Dict[str, str] | None = None


def _prompt_path() -> Path:
    prep_cfg = get_config_section("prep")
    path = Path(prep_cfg.get("prompt", "src/Deepseek/prompt/prep_prompt_deepseek_en.xml"))
    return path if path.is_absolute() else PIPELINE_ROOT / path


def _raw_prompt() -> str:
    global _raw_prompt_cache
    if _raw_prompt_cache is None:
        _raw_prompt_cache = _prompt_path().read_text(encoding="utf-8")
    return _raw_prompt_cache


def _section(tag: str) -> str:
    pattern = _SECTION_RE_CACHE.setdefault(
        tag, re.compile(rf"<{tag}[^>]*>(.*?)</{tag}>", re.DOTALL)
    )
    match = pattern.search(_raw_prompt())
    if not match:
        raise PromptSchemaError(f"<{tag}> section not found in {_prompt_path()}")
    return match.group(1).strip()


def _block_schema() -> Dict[str, str]:
    global _block_schema_cache
    if _block_schema_cache is None:
        schema_section = _section("BLOCK_SCHEMA")
        _block_schema_cache = {
            name: body.strip() for name, body in _BLOCK_RE.findall(schema_section)
        }
        missing = [b for b in (*PRO_BLOCKS, *FLASH_BLOCKS) if b not in _block_schema_cache]
        if missing:
            raise PromptSchemaError(
                f"BLOCK_SCHEMA in {_prompt_path()} is missing block(s) {missing} — "
                f"block_prompts.py's PRO_BLOCKS/FLASH_BLOCKS has drifted from the prompt file."
            )
    return _block_schema_cache


def block_schema_text(block_name: str) -> str:
    """The exact <block name="..."> instruction body for one block."""
    return _block_schema()[block_name]


_PRO_TASK_NOTE = (
    "name_map must be exhaustive — every proper noun (not just named cast) that recurs across "
    "chapters, since name_map is the injected context every downstream Flash call trusts as the "
    "authoritative JP->EN table. If bible_context supplies characters already locked from a "
    "prior volume, reuse their canonical_name and en spelling exactly; do not rename them."
)


# ══════════════════════════════════════════════════════════════════════════
# ONE system prompt for every call in a run — Pro's root extraction and every
# Flash block fill alike. No model- or task-specific text may live here; that
# would break the byte-identical prefix every call after the first needs to
# reuse. See module docstring.
# ══════════════════════════════════════════════════════════════════════════

def build_shared_system_prompt() -> str:
    role = _section("ROLE")
    policy = _section("LOCALIZATION_POLICY")
    return (
        "<ROLE>\n" + role + "\n\n"
        "You are being called as one step of a cache-warmed, multi-call prep run — a different "
        "call in this same run may already have extracted <character_roster> and <name_map> "
        "(injected into your user turn as <injected_character_roster> when so). Your job this "
        "turn is to produce exactly the block(s) named in the trailing <BLOCK_TASK> section, "
        "nothing else.\n"
        "</ROLE>\n\n"
        "<LOCALIZATION_POLICY>\n" + policy + "\n</LOCALIZATION_POLICY>\n\n"
        "<OUTPUT_CONTRACT>\n"
        "Your user turn contains, in this fixed order: <jp_chapters> (full JP text of every "
        "chapter), optionally <bible_context> (present only for sequel volumes — a JSON dump of "
        "the series bible's term_lock/verbatim_anchors/voice_fingerprints accumulated from prior "
        "volumes; anything in it is AUTHORITATIVE — extend it, never rename or reinterpret a "
        "character or anchor it already locks), optionally <injected_character_roster> (present "
        "whenever a prior call in this run has already extracted character_roster — treat every "
        "canonical_name in it as locked, do not rename or reinterpret), and a trailing "
        "<BLOCK_TASK blocks=\"...\"> naming the block(s) you must produce this turn, with each "
        "one's schema rules inline.\n\n"
        "Return ONLY those top-level XML element(s), back to back if more than one, no markdown "
        "fences, no commentary, no document wrapper. The FIRST character of your response is "
        "`<`. If the source genuinely does not support a confident answer for a block (e.g. no "
        "illustration markers in this volume), return that block in pending shape instead of "
        "inventing content: <BLOCK_NAME status=\"pending\"><pending>reason</pending></BLOCK_NAME>. "
        "A missing block is honest; a fabricated one corrupts the translator's context.\n\n"
        "Read every chapter before writing any block — character_roster, name_map, and "
        "voice_fingerprints in particular are wrong if built from chapter 1 alone and a name or "
        "role shifts later in the volume.\n"
        "</OUTPUT_CONTRACT>"
    )


def build_task_suffix(block_names: Tuple[str, ...], *, extra_note: str = "") -> str:
    schema = _block_schema()
    body = "\n\n".join(
        f"Fill the <{name}> block.\n\n{schema[name]}" for name in block_names
    )
    note = f"\n\n{extra_note}" if extra_note else ""
    return f'<BLOCK_TASK blocks="{",".join(block_names)}">\n{body}{note}\n</BLOCK_TASK>'


# ══════════════════════════════════════════════════════════════════════════
# Multi-turn prep — one persisted, sequential DeepSeekConversationManager
# turn per block (src/prep/multiturn_agent.py), instead of the parallel
# path's independent concurrent calls. Every turn's response is a small JSON
# node envelope (see src/prep/json_xml_node.py), not raw XML — the ONE thing
# that differs from build_shared_system_prompt() above; ROLE, LOCALIZATION_
# POLICY, and every block's schema text are still read from the exact same
# source (prep_prompt_deepseek_en.xml via _section()/_block_schema()), so
# the block content rules never get defined twice.
# ══════════════════════════════════════════════════════════════════════════

def build_multiturn_system_prompt() -> str:
    role = _section("ROLE")
    policy = _section("LOCALIZATION_POLICY")
    return (
        "<ROLE>\n" + role + "\n\n"
        "You are being called as one turn of a persisted, SEQUENTIAL, multi-turn prep "
        "conversation — one call per context.xml block, always in the same fixed order. "
        "Every earlier turn's own output is already visible to you in this conversation's "
        "history (the raw JSON envelope it returned) — treat any character, name, or fact "
        "a prior turn already committed as LOCKED. Reuse it exactly; never rename or "
        "reinterpret it just because this turn's block gives you room to.\n"
        "</ROLE>\n\n"
        "<LOCALIZATION_POLICY>\n" + policy + "\n</LOCALIZATION_POLICY>\n\n"
        "<OUTPUT_CONTRACT>\n"
        "The FIRST turn's user message additionally carries <jp_chapters> (full JP text of "
        "every chapter) and, for sequel volumes, <bible_context> — a JSON dump of the series "
        "bible's term_lock/verbatim_anchors/voice_fingerprints accumulated from prior volumes; "
        "anything in it is AUTHORITATIVE — extend it, never rename or reinterpret a character "
        "or anchor it already locks. Every turn's user message ends with a <BLOCK_TASK> naming "
        "the ONE block you must produce this turn, with that block's schema rules inline.\n\n"
        "Return ONLY a single JSON object — no markdown fences, no commentary, no document "
        "wrapper. The FIRST character of your response is `{`. Shape:\n"
        '  {"tag": "BLOCK_NAME", "attrs": {...}, "text": "...", "children": [...]}\n'
        "`attrs`, `text`, and `children` are all optional; every entry in `children` is a node "
        "in this exact same shape. This JSON tree IS the block's XML element — `tag` is the "
        "element name, `attrs` its attributes, `text` its own text content, `children` its "
        "nested elements in order. Encode the block's schema below as this tree exactly like "
        "you would write it as XML; do not flatten or reshape it into a different JSON "
        "convention.\n\n"
        "If the source genuinely does not support a confident answer for this block, return it "
        'in pending shape instead of inventing content: {"tag": "BLOCK_NAME", "attrs": '
        '{"status": "pending"}, "children": [{"tag": "pending", "text": "reason"}]}. A missing '
        "block is honest; a fabricated one corrupts the translator's context.\n\n"
        "Read every chapter before writing any block — character_roster, name_map, and "
        "voice_fingerprints in particular are wrong if built from chapter 1 alone and a name or "
        "role shifts later in the volume.\n"
        "</OUTPUT_CONTRACT>"
    )


def build_multiturn_task_suffix(block_name: str, *, extra_note: str = "") -> str:
    schema = block_schema_text(block_name)
    note = f"\n\n{extra_note}" if extra_note else ""
    return (
        f'<BLOCK_TASK blocks="{block_name}">\n'
        f"Fill the <{block_name}> block, encoded as the JSON node envelope described in "
        f"OUTPUT_CONTRACT.\n\n{schema}{note}\n"
        "</BLOCK_TASK>"
    )


# ══════════════════════════════════════════════════════════════════════════
# Shared leading prefix — jp_chapters + optional bible_context. Byte-identical
# whether it's about to be followed by Pro's root-extraction task or Flash's
# injected_character_roster + block task; that shared leading run is exactly
# what lets Pro's own call warm cache for every Flash call that follows.
# ══════════════════════════════════════════════════════════════════════════

def build_shared_prefix(jp_chapters_block: str, bible_block: str = "") -> str:
    parts = [jp_chapters_block]
    if bible_block:
        parts.append(bible_block)
    return "\n\n".join(parts)


def build_pro_user_message(shared_prefix: str) -> str:
    return f"{shared_prefix}\n\n{build_task_suffix(PRO_BLOCKS, extra_note=_PRO_TASK_NOTE)}"


def build_flash_common_prefix(shared_prefix: str, injected_roster_xml: str) -> str:
    """Extends the shared prefix with the one thing Pro's own call never has
    (its own output). Build ONCE per prep run, reuse the identical string for
    every Flash call — that identity is what Test A confirmed works
    (Flash-to-Flash cache reuse). shared_prefix being an exact leading
    substring of this is the Pro-to-Flash half the module docstring flags as
    UNCONFIRMED (Test C contradicted Test B on this specific question)."""
    return f"{shared_prefix}\n\n<injected_character_roster>\n{injected_roster_xml}\n</injected_character_roster>"


def build_flash_user_message(common_prefix: str, block_name: str) -> str:
    return f"{common_prefix}\n\n{build_task_suffix((block_name,))}"
